// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MassoudBooksSr.proto

package MassoudBookSerialization;

public final class MassoudBooksSr {
  private MassoudBooksSr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MassoudBookSerialization.Book)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string catagory = 2;</code>
     */
    java.lang.String getCatagory();
    /**
     * <code>string catagory = 2;</code>
     */
    com.google.protobuf.ByteString
        getCatagoryBytes();

    /**
     * <code>string readingStatus = 3;</code>
     */
    java.lang.String getReadingStatus();
    /**
     * <code>string readingStatus = 3;</code>
     */
    com.google.protobuf.ByteString
        getReadingStatusBytes();

    /**
     * <code>repeated string tag = 4;</code>
     */
    java.util.List<java.lang.String>
        getTagList();
    /**
     * <code>repeated string tag = 4;</code>
     */
    int getTagCount();
    /**
     * <code>repeated string tag = 4;</code>
     */
    java.lang.String getTag(int index);
    /**
     * <code>repeated string tag = 4;</code>
     */
    com.google.protobuf.ByteString
        getTagBytes(int index);

    /**
     * <code>int32 pages = 5;</code>
     */
    int getPages();
  }
  /**
   * Protobuf type {@code MassoudBookSerialization.Book}
   */
  public  static final class Book extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MassoudBookSerialization.Book)
      BookOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Book.newBuilder() to construct.
    private Book(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Book() {
      name_ = "";
      catagory_ = "";
      readingStatus_ = "";
      tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      pages_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Book(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              catagory_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              readingStatus_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                tag_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              tag_.add(s);
              break;
            }
            case 40: {

              pages_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          tag_ = tag_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MassoudBookSerialization.MassoudBooksSr.Book.class, MassoudBookSerialization.MassoudBooksSr.Book.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATAGORY_FIELD_NUMBER = 2;
    private volatile java.lang.Object catagory_;
    /**
     * <code>string catagory = 2;</code>
     */
    public java.lang.String getCatagory() {
      java.lang.Object ref = catagory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catagory_ = s;
        return s;
      }
    }
    /**
     * <code>string catagory = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCatagoryBytes() {
      java.lang.Object ref = catagory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catagory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int READINGSTATUS_FIELD_NUMBER = 3;
    private volatile java.lang.Object readingStatus_;
    /**
     * <code>string readingStatus = 3;</code>
     */
    public java.lang.String getReadingStatus() {
      java.lang.Object ref = readingStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        readingStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string readingStatus = 3;</code>
     */
    public com.google.protobuf.ByteString
        getReadingStatusBytes() {
      java.lang.Object ref = readingStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        readingStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList tag_;
    /**
     * <code>repeated string tag = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTagList() {
      return tag_;
    }
    /**
     * <code>repeated string tag = 4;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated string tag = 4;</code>
     */
    public java.lang.String getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated string tag = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTagBytes(int index) {
      return tag_.getByteString(index);
    }

    public static final int PAGES_FIELD_NUMBER = 5;
    private int pages_;
    /**
     * <code>int32 pages = 5;</code>
     */
    public int getPages() {
      return pages_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getCatagoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, catagory_);
      }
      if (!getReadingStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, readingStatus_);
      }
      for (int i = 0; i < tag_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tag_.getRaw(i));
      }
      if (pages_ != 0) {
        output.writeInt32(5, pages_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getCatagoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, catagory_);
      }
      if (!getReadingStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, readingStatus_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tag_.size(); i++) {
          dataSize += computeStringSizeNoTag(tag_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagList().size();
      }
      if (pages_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, pages_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MassoudBookSerialization.MassoudBooksSr.Book)) {
        return super.equals(obj);
      }
      MassoudBookSerialization.MassoudBooksSr.Book other = (MassoudBookSerialization.MassoudBooksSr.Book) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getCatagory()
          .equals(other.getCatagory());
      result = result && getReadingStatus()
          .equals(other.getReadingStatus());
      result = result && getTagList()
          .equals(other.getTagList());
      result = result && (getPages()
          == other.getPages());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CATAGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCatagory().hashCode();
      hash = (37 * hash) + READINGSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getReadingStatus().hashCode();
      if (getTagCount() > 0) {
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTagList().hashCode();
      }
      hash = (37 * hash) + PAGES_FIELD_NUMBER;
      hash = (53 * hash) + getPages();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MassoudBookSerialization.MassoudBooksSr.Book parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MassoudBookSerialization.MassoudBooksSr.Book prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MassoudBookSerialization.Book}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MassoudBookSerialization.Book)
        MassoudBookSerialization.MassoudBooksSr.BookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_Book_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_Book_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MassoudBookSerialization.MassoudBooksSr.Book.class, MassoudBookSerialization.MassoudBooksSr.Book.Builder.class);
      }

      // Construct using MassoudBookSerialization.MassoudBooksSr.Book.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        catagory_ = "";

        readingStatus_ = "";

        tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        pages_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_Book_descriptor;
      }

      @java.lang.Override
      public MassoudBookSerialization.MassoudBooksSr.Book getDefaultInstanceForType() {
        return MassoudBookSerialization.MassoudBooksSr.Book.getDefaultInstance();
      }

      @java.lang.Override
      public MassoudBookSerialization.MassoudBooksSr.Book build() {
        MassoudBookSerialization.MassoudBooksSr.Book result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MassoudBookSerialization.MassoudBooksSr.Book buildPartial() {
        MassoudBookSerialization.MassoudBooksSr.Book result = new MassoudBookSerialization.MassoudBooksSr.Book(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.catagory_ = catagory_;
        result.readingStatus_ = readingStatus_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          tag_ = tag_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.tag_ = tag_;
        result.pages_ = pages_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MassoudBookSerialization.MassoudBooksSr.Book) {
          return mergeFrom((MassoudBookSerialization.MassoudBooksSr.Book)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MassoudBookSerialization.MassoudBooksSr.Book other) {
        if (other == MassoudBookSerialization.MassoudBooksSr.Book.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getCatagory().isEmpty()) {
          catagory_ = other.catagory_;
          onChanged();
        }
        if (!other.getReadingStatus().isEmpty()) {
          readingStatus_ = other.readingStatus_;
          onChanged();
        }
        if (!other.tag_.isEmpty()) {
          if (tag_.isEmpty()) {
            tag_ = other.tag_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureTagIsMutable();
            tag_.addAll(other.tag_);
          }
          onChanged();
        }
        if (other.getPages() != 0) {
          setPages(other.getPages());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MassoudBookSerialization.MassoudBooksSr.Book parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MassoudBookSerialization.MassoudBooksSr.Book) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object catagory_ = "";
      /**
       * <code>string catagory = 2;</code>
       */
      public java.lang.String getCatagory() {
        java.lang.Object ref = catagory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          catagory_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string catagory = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCatagoryBytes() {
        java.lang.Object ref = catagory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          catagory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string catagory = 2;</code>
       */
      public Builder setCatagory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        catagory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string catagory = 2;</code>
       */
      public Builder clearCatagory() {
        
        catagory_ = getDefaultInstance().getCatagory();
        onChanged();
        return this;
      }
      /**
       * <code>string catagory = 2;</code>
       */
      public Builder setCatagoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        catagory_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object readingStatus_ = "";
      /**
       * <code>string readingStatus = 3;</code>
       */
      public java.lang.String getReadingStatus() {
        java.lang.Object ref = readingStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          readingStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string readingStatus = 3;</code>
       */
      public com.google.protobuf.ByteString
          getReadingStatusBytes() {
        java.lang.Object ref = readingStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          readingStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string readingStatus = 3;</code>
       */
      public Builder setReadingStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        readingStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string readingStatus = 3;</code>
       */
      public Builder clearReadingStatus() {
        
        readingStatus_ = getDefaultInstance().getReadingStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string readingStatus = 3;</code>
       */
      public Builder setReadingStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        readingStatus_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          tag_ = new com.google.protobuf.LazyStringArrayList(tag_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTagList() {
        return tag_.getUnmodifiableView();
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public int getTagCount() {
        return tag_.size();
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public java.lang.String getTag(int index) {
        return tag_.get(index);
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTagBytes(int index) {
        return tag_.getByteString(index);
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public Builder setTag(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
        tag_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public Builder addTag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
        tag_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public Builder addAllTag(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tag_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public Builder clearTag() {
        tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string tag = 4;</code>
       */
      public Builder addTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTagIsMutable();
        tag_.add(value);
        onChanged();
        return this;
      }

      private int pages_ ;
      /**
       * <code>int32 pages = 5;</code>
       */
      public int getPages() {
        return pages_;
      }
      /**
       * <code>int32 pages = 5;</code>
       */
      public Builder setPages(int value) {
        
        pages_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pages = 5;</code>
       */
      public Builder clearPages() {
        
        pages_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MassoudBookSerialization.Book)
    }

    // @@protoc_insertion_point(class_scope:MassoudBookSerialization.Book)
    private static final MassoudBookSerialization.MassoudBooksSr.Book DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MassoudBookSerialization.MassoudBooksSr.Book();
    }

    public static MassoudBookSerialization.MassoudBooksSr.Book getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Book>
        PARSER = new com.google.protobuf.AbstractParser<Book>() {
      @java.lang.Override
      public Book parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Book(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Book> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Book> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MassoudBookSerialization.MassoudBooksSr.Book getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ToSerializeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MassoudBookSerialization.ToSerialize)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    java.util.List<MassoudBookSerialization.MassoudBooksSr.Book> 
        getAllBooksList();
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    MassoudBookSerialization.MassoudBooksSr.Book getAllBooks(int index);
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    int getAllBooksCount();
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    java.util.List<? extends MassoudBookSerialization.MassoudBooksSr.BookOrBuilder> 
        getAllBooksOrBuilderList();
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    MassoudBookSerialization.MassoudBooksSr.BookOrBuilder getAllBooksOrBuilder(
        int index);

    /**
     * <code>repeated string Tags = 2;</code>
     */
    java.util.List<java.lang.String>
        getTagsList();
    /**
     * <code>repeated string Tags = 2;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated string Tags = 2;</code>
     */
    java.lang.String getTags(int index);
    /**
     * <code>repeated string Tags = 2;</code>
     */
    com.google.protobuf.ByteString
        getTagsBytes(int index);
  }
  /**
   * Protobuf type {@code MassoudBookSerialization.ToSerialize}
   */
  public  static final class ToSerialize extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MassoudBookSerialization.ToSerialize)
      ToSerializeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToSerialize.newBuilder() to construct.
    private ToSerialize(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToSerialize() {
      allBooks_ = java.util.Collections.emptyList();
      tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToSerialize(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                allBooks_ = new java.util.ArrayList<MassoudBookSerialization.MassoudBooksSr.Book>();
                mutable_bitField0_ |= 0x00000001;
              }
              allBooks_.add(
                  input.readMessage(MassoudBookSerialization.MassoudBooksSr.Book.parser(), extensionRegistry));
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                tags_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              tags_.add(s);
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          allBooks_ = java.util.Collections.unmodifiableList(allBooks_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          tags_ = tags_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_ToSerialize_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_ToSerialize_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MassoudBookSerialization.MassoudBooksSr.ToSerialize.class, MassoudBookSerialization.MassoudBooksSr.ToSerialize.Builder.class);
    }

    public static final int ALLBOOKS_FIELD_NUMBER = 1;
    private java.util.List<MassoudBookSerialization.MassoudBooksSr.Book> allBooks_;
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    public java.util.List<MassoudBookSerialization.MassoudBooksSr.Book> getAllBooksList() {
      return allBooks_;
    }
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    public java.util.List<? extends MassoudBookSerialization.MassoudBooksSr.BookOrBuilder> 
        getAllBooksOrBuilderList() {
      return allBooks_;
    }
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    public int getAllBooksCount() {
      return allBooks_.size();
    }
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    public MassoudBookSerialization.MassoudBooksSr.Book getAllBooks(int index) {
      return allBooks_.get(index);
    }
    /**
     * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
     */
    public MassoudBookSerialization.MassoudBooksSr.BookOrBuilder getAllBooksOrBuilder(
        int index) {
      return allBooks_.get(index);
    }

    public static final int TAGS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList tags_;
    /**
     * <code>repeated string Tags = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated string Tags = 2;</code>
     */
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated string Tags = 2;</code>
     */
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated string Tags = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTagsBytes(int index) {
      return tags_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < allBooks_.size(); i++) {
        output.writeMessage(1, allBooks_.get(i));
      }
      for (int i = 0; i < tags_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tags_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < allBooks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, allBooks_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tags_.size(); i++) {
          dataSize += computeStringSizeNoTag(tags_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MassoudBookSerialization.MassoudBooksSr.ToSerialize)) {
        return super.equals(obj);
      }
      MassoudBookSerialization.MassoudBooksSr.ToSerialize other = (MassoudBookSerialization.MassoudBooksSr.ToSerialize) obj;

      boolean result = true;
      result = result && getAllBooksList()
          .equals(other.getAllBooksList());
      result = result && getTagsList()
          .equals(other.getTagsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAllBooksCount() > 0) {
        hash = (37 * hash) + ALLBOOKS_FIELD_NUMBER;
        hash = (53 * hash) + getAllBooksList().hashCode();
      }
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MassoudBookSerialization.MassoudBooksSr.ToSerialize prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MassoudBookSerialization.ToSerialize}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MassoudBookSerialization.ToSerialize)
        MassoudBookSerialization.MassoudBooksSr.ToSerializeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_ToSerialize_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_ToSerialize_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MassoudBookSerialization.MassoudBooksSr.ToSerialize.class, MassoudBookSerialization.MassoudBooksSr.ToSerialize.Builder.class);
      }

      // Construct using MassoudBookSerialization.MassoudBooksSr.ToSerialize.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAllBooksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (allBooksBuilder_ == null) {
          allBooks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          allBooksBuilder_.clear();
        }
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MassoudBookSerialization.MassoudBooksSr.internal_static_MassoudBookSerialization_ToSerialize_descriptor;
      }

      @java.lang.Override
      public MassoudBookSerialization.MassoudBooksSr.ToSerialize getDefaultInstanceForType() {
        return MassoudBookSerialization.MassoudBooksSr.ToSerialize.getDefaultInstance();
      }

      @java.lang.Override
      public MassoudBookSerialization.MassoudBooksSr.ToSerialize build() {
        MassoudBookSerialization.MassoudBooksSr.ToSerialize result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MassoudBookSerialization.MassoudBooksSr.ToSerialize buildPartial() {
        MassoudBookSerialization.MassoudBooksSr.ToSerialize result = new MassoudBookSerialization.MassoudBooksSr.ToSerialize(this);
        int from_bitField0_ = bitField0_;
        if (allBooksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            allBooks_ = java.util.Collections.unmodifiableList(allBooks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.allBooks_ = allBooks_;
        } else {
          result.allBooks_ = allBooksBuilder_.build();
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          tags_ = tags_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tags_ = tags_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MassoudBookSerialization.MassoudBooksSr.ToSerialize) {
          return mergeFrom((MassoudBookSerialization.MassoudBooksSr.ToSerialize)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MassoudBookSerialization.MassoudBooksSr.ToSerialize other) {
        if (other == MassoudBookSerialization.MassoudBooksSr.ToSerialize.getDefaultInstance()) return this;
        if (allBooksBuilder_ == null) {
          if (!other.allBooks_.isEmpty()) {
            if (allBooks_.isEmpty()) {
              allBooks_ = other.allBooks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAllBooksIsMutable();
              allBooks_.addAll(other.allBooks_);
            }
            onChanged();
          }
        } else {
          if (!other.allBooks_.isEmpty()) {
            if (allBooksBuilder_.isEmpty()) {
              allBooksBuilder_.dispose();
              allBooksBuilder_ = null;
              allBooks_ = other.allBooks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              allBooksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAllBooksFieldBuilder() : null;
            } else {
              allBooksBuilder_.addAllMessages(other.allBooks_);
            }
          }
        }
        if (!other.tags_.isEmpty()) {
          if (tags_.isEmpty()) {
            tags_ = other.tags_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTagsIsMutable();
            tags_.addAll(other.tags_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MassoudBookSerialization.MassoudBooksSr.ToSerialize parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MassoudBookSerialization.MassoudBooksSr.ToSerialize) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<MassoudBookSerialization.MassoudBooksSr.Book> allBooks_ =
        java.util.Collections.emptyList();
      private void ensureAllBooksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          allBooks_ = new java.util.ArrayList<MassoudBookSerialization.MassoudBooksSr.Book>(allBooks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          MassoudBookSerialization.MassoudBooksSr.Book, MassoudBookSerialization.MassoudBooksSr.Book.Builder, MassoudBookSerialization.MassoudBooksSr.BookOrBuilder> allBooksBuilder_;

      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public java.util.List<MassoudBookSerialization.MassoudBooksSr.Book> getAllBooksList() {
        if (allBooksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(allBooks_);
        } else {
          return allBooksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public int getAllBooksCount() {
        if (allBooksBuilder_ == null) {
          return allBooks_.size();
        } else {
          return allBooksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public MassoudBookSerialization.MassoudBooksSr.Book getAllBooks(int index) {
        if (allBooksBuilder_ == null) {
          return allBooks_.get(index);
        } else {
          return allBooksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder setAllBooks(
          int index, MassoudBookSerialization.MassoudBooksSr.Book value) {
        if (allBooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBooksIsMutable();
          allBooks_.set(index, value);
          onChanged();
        } else {
          allBooksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder setAllBooks(
          int index, MassoudBookSerialization.MassoudBooksSr.Book.Builder builderForValue) {
        if (allBooksBuilder_ == null) {
          ensureAllBooksIsMutable();
          allBooks_.set(index, builderForValue.build());
          onChanged();
        } else {
          allBooksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder addAllBooks(MassoudBookSerialization.MassoudBooksSr.Book value) {
        if (allBooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBooksIsMutable();
          allBooks_.add(value);
          onChanged();
        } else {
          allBooksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder addAllBooks(
          int index, MassoudBookSerialization.MassoudBooksSr.Book value) {
        if (allBooksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAllBooksIsMutable();
          allBooks_.add(index, value);
          onChanged();
        } else {
          allBooksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder addAllBooks(
          MassoudBookSerialization.MassoudBooksSr.Book.Builder builderForValue) {
        if (allBooksBuilder_ == null) {
          ensureAllBooksIsMutable();
          allBooks_.add(builderForValue.build());
          onChanged();
        } else {
          allBooksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder addAllBooks(
          int index, MassoudBookSerialization.MassoudBooksSr.Book.Builder builderForValue) {
        if (allBooksBuilder_ == null) {
          ensureAllBooksIsMutable();
          allBooks_.add(index, builderForValue.build());
          onChanged();
        } else {
          allBooksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder addAllAllBooks(
          java.lang.Iterable<? extends MassoudBookSerialization.MassoudBooksSr.Book> values) {
        if (allBooksBuilder_ == null) {
          ensureAllBooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, allBooks_);
          onChanged();
        } else {
          allBooksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder clearAllBooks() {
        if (allBooksBuilder_ == null) {
          allBooks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          allBooksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public Builder removeAllBooks(int index) {
        if (allBooksBuilder_ == null) {
          ensureAllBooksIsMutable();
          allBooks_.remove(index);
          onChanged();
        } else {
          allBooksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public MassoudBookSerialization.MassoudBooksSr.Book.Builder getAllBooksBuilder(
          int index) {
        return getAllBooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public MassoudBookSerialization.MassoudBooksSr.BookOrBuilder getAllBooksOrBuilder(
          int index) {
        if (allBooksBuilder_ == null) {
          return allBooks_.get(index);  } else {
          return allBooksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public java.util.List<? extends MassoudBookSerialization.MassoudBooksSr.BookOrBuilder> 
           getAllBooksOrBuilderList() {
        if (allBooksBuilder_ != null) {
          return allBooksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(allBooks_);
        }
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public MassoudBookSerialization.MassoudBooksSr.Book.Builder addAllBooksBuilder() {
        return getAllBooksFieldBuilder().addBuilder(
            MassoudBookSerialization.MassoudBooksSr.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public MassoudBookSerialization.MassoudBooksSr.Book.Builder addAllBooksBuilder(
          int index) {
        return getAllBooksFieldBuilder().addBuilder(
            index, MassoudBookSerialization.MassoudBooksSr.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .MassoudBookSerialization.Book AllBooks = 1;</code>
       */
      public java.util.List<MassoudBookSerialization.MassoudBooksSr.Book.Builder> 
           getAllBooksBuilderList() {
        return getAllBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          MassoudBookSerialization.MassoudBooksSr.Book, MassoudBookSerialization.MassoudBooksSr.Book.Builder, MassoudBookSerialization.MassoudBooksSr.BookOrBuilder> 
          getAllBooksFieldBuilder() {
        if (allBooksBuilder_ == null) {
          allBooksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              MassoudBookSerialization.MassoudBooksSr.Book, MassoudBookSerialization.MassoudBooksSr.Book.Builder, MassoudBookSerialization.MassoudBooksSr.BookOrBuilder>(
                  allBooks_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          allBooks_ = null;
        }
        return allBooksBuilder_;
      }

      private com.google.protobuf.LazyStringList tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tags_ = new com.google.protobuf.LazyStringArrayList(tags_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTagsList() {
        return tags_.getUnmodifiableView();
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public int getTagsCount() {
        return tags_.size();
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public java.lang.String getTags(int index) {
        return tags_.get(index);
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTagsBytes(int index) {
        return tags_.getByteString(index);
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public Builder setTags(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public Builder addTags(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<java.lang.String> values) {
        ensureTagsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tags_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public Builder clearTags() {
        tags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string Tags = 2;</code>
       */
      public Builder addTagsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTagsIsMutable();
        tags_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MassoudBookSerialization.ToSerialize)
    }

    // @@protoc_insertion_point(class_scope:MassoudBookSerialization.ToSerialize)
    private static final MassoudBookSerialization.MassoudBooksSr.ToSerialize DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MassoudBookSerialization.MassoudBooksSr.ToSerialize();
    }

    public static MassoudBookSerialization.MassoudBooksSr.ToSerialize getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToSerialize>
        PARSER = new com.google.protobuf.AbstractParser<ToSerialize>() {
      @java.lang.Override
      public ToSerialize parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ToSerialize(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToSerialize> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToSerialize> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MassoudBookSerialization.MassoudBooksSr.ToSerialize getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MassoudBookSerialization_Book_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MassoudBookSerialization_Book_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MassoudBookSerialization_ToSerialize_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MassoudBookSerialization_ToSerialize_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024MassoudBooksSr.proto\022\030MassoudBookSeria" +
      "lization\"Y\n\004Book\022\014\n\004name\030\001 \001(\t\022\020\n\010catago" +
      "ry\030\002 \001(\t\022\025\n\rreadingStatus\030\003 \001(\t\022\013\n\003tag\030\004" +
      " \003(\t\022\r\n\005pages\030\005 \001(\005\"M\n\013ToSerialize\0220\n\010Al" +
      "lBooks\030\001 \003(\0132\036.MassoudBookSerialization." +
      "Book\022\014\n\004Tags\030\002 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MassoudBookSerialization_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MassoudBookSerialization_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MassoudBookSerialization_Book_descriptor,
        new java.lang.String[] { "Name", "Catagory", "ReadingStatus", "Tag", "Pages", });
    internal_static_MassoudBookSerialization_ToSerialize_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MassoudBookSerialization_ToSerialize_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MassoudBookSerialization_ToSerialize_descriptor,
        new java.lang.String[] { "AllBooks", "Tags", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
